build:
  modules:
    - boost
    - ninja
    - python3
    - qt
    - cmake/new
  dependencies:
    - ecmwf/ecbuild@develop
  parallel: 64
  cmake_options:
    - -DENABLE_ALL_TESTS=ON
  ctest_options:
    - -L nightly
